package iss.sa42.team8.model;
// Generated 3 Jun, 2016 11:59:38 PM by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */

@Entity
@Table(name = "category")
public class Category {

	@Id
	@Column(name = "categoryID")
	private String categoryID;
	@Column(name = "categoryName")
	private String categoryName;
	@Column(name = "remarks")
	private String remarks;

	public Category() {
	}

	public Category(String categoryID, String categoryName) {
		super();
		this.categoryID = categoryID;
		this.categoryName = categoryName;
	}

	public Category(String categoryID, String categoryName, String remarks) {
		super();
		this.categoryID = categoryID;
		this.categoryName = categoryName;
		this.remarks = remarks;
	}

	public String getCategoryID() {
		return categoryID;
	}

	public void setCategoryID(String categoryID) {
		this.categoryID = categoryID;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}
