package iss.sa42.team8.model;
// Generated 3 Jun, 2016 11:59:38 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.hibernate.validator.constraints.NotEmpty;

/**
 * Facility generated by hbm2java
 */

@Entity
public class Facility {
	
	public static final String VACANT = "vacant";
	public static final String BOOKED = "booked";
	public static final String UNDER_MAINTENANCE = "under_maintenance";
	public static final String FACILITY_PREFIX = "F";
	
	@Id
//	@GeneratedValue(strategy = GenerationType.AUTO)
	private String facilityID;
//	@NotEmpty
	@Column(name = "categoryID")
	private String categoryID;
//	@NotEmpty
	@Column(name = "facilityName")
	private String facilityName;
//	@NotEmpty
	@Column(name = "status")
	private String status;
	@Column(name = "remarks")
	private String remarks;

	public Facility() {
		super();
	}

	public Facility(String facilityID, String categoryID, String facilityName, String status) {
		super();
		this.facilityID = facilityID;
		this.categoryID = categoryID;
		this.facilityName = facilityName;
		this.status = status;
	}

	public Facility(String facilityID, String categoryID, String facilityName, String status, String remarks) {
		super();
		this.facilityID = facilityID;
		this.categoryID = categoryID;
		this.facilityName = facilityName;
		this.status = status;
		this.remarks = remarks;
	}

	public String getFacilityID() {
		return facilityID;
	}

	public void setFacilityID(String facilityID) {
		this.facilityID = facilityID;
	}

	public String getCategoryID() {
		return categoryID;
	}

	public void setCategoryID(String categoryID) {
		this.categoryID = categoryID;
	}

	public String getFacilityName() {
		return facilityName;
	}

	public void setFacilityName(String facilityName) {
		this.facilityName = facilityName;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemarks() {
		return remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
}
